### ISSUE TITLE
Unstable, random very results when refresh a webpage

### ISSUE THREAD

**Issue by pascalandy** [tpbowden/swarm-ingress-router#13]
I get very random very results when refresh a webpage.

I prepared a video http://jmp.sh/wAJ0nXw
and the screen shots from pingdom tools http://jmp.sh/85eUVKZ

**Comment by bvis** [comment]
I think there's a bug in the "latest" version of the container. @pascalandy maybe you could try the v0.2.0 version and check if it works for you.

**Comment by tpbowden** [comment]
I've reverted the latest broken commit, should be back to normal on latest now.

**Comment by pascalandy** [comment]
Will do thanks! 

P.S. why closing this issue this fast ?

**Comment by tpbowden** [comment]
I've closed it because (as far as I can tell) the problem you've described was fixed when I rolled back the project to the previous stable version. Hopefully it won't be re introduced when I re-implement the feature which caused the problem in the first place.

**Comment by pascalandy** [comment]
Thanks for the your explanation :)

To follow, using tag v.0.3.0, everything is rock solid! Love you!
