### ISSUE TITLE
Forcing a service to use SSL

### ISSUE THREAD

**Issue by joskfg** [tpbowden/swarm-ingress-router#14]
I was trying to create a service with this config

```
docker service create \
--name=varnish \
--network=router-proxy \
--label ingress=true \
--label ingress.dnsname=my.domain.com \
--label ingress.targetport=80 \
--label ingress.forcessl=true \
--label ingress.tls=true \
--label ingress.cert="MY-CERT" \
--label ingress.key="MY-SECRET-KEY" \
my-image
```

After that I can access to `https://my.domain.com` without problem but I expect when I access to ` http://my.domain.com` (NO SSL) it would be redirected to `http://my.domain.com` because the `--label ingress.tls=true`.

**Current Behaviour**
`ingress.tls=true`doesn't redirecto to `HTTPS`

**Expected Behaviour**
`ingress.tls=true` redirects from `HTTP` to `HTTPS`

**Comment by tpbowden** [comment]
You've put 'ingress.forcessl' instead of 'ingress.forcetls'

**Comment by joskfg** [comment]
You are right! In some moment it changed in my configuration and didn't notice. Thanks for the support and great work!
