### ISSUE TITLE
Random error > "Failed to look up service"

### ISSUE THREAD

**Issue by pascalandy** [tpbowden/swarm-ingress-router#16]
I'm following on this [issue](https://github.com/tpbowden/swarm-ingress-router/issues/13). I'm testing/using this reverse-proxy a lot since 13 days. I have to report that it's not stable. Here are the docker service [commands](https://gist.github.com/pascalandy/42e655cf4a00510538d8e466dacdc40e) I'm using.

When I check the logs, I see something is wrong. Please [watch](http://jmp.sh/2cR42S1) this video cast.

```
ctnID=$(docker ps -q --filter label=com.docker.swarm.service.name=router) && \
docker logs --follow $ctnID
```

In the test you can see, there is only one container for _pingme_. I have the same issue when I do `docker service scale pingme=2`.

Hope you this help. BTW, is there any other logs I could check ?

Cheers!

**Comment by tpbowden** [comment]
It look like there is something going wrong each time the routes are synced with Redis causing the connections to drop. I'll look into it, thanks for the details.

**Comment by tpbowden** [comment]
In terms of extra logs, you can only see the logs coming from the containers. If you want to fork the project you could easily add more debug logs all over the place to try and pinpoint the issue.

**Comment by pascalandy** [comment]
Let me know if I can help testing this further more. Per example, would different Redis (using redis:3.2.3-alpine at the moment) version change something?

**Comment by tpbowden** [comment]
No I think the issue is in the code when the router picks up the updated services from redis every few seconds. Won't have time to look into it properly until next weekend though I'm afraid.

**Comment by pascalandy** [comment]
thx for the follow up!

**Comment by tpbowden** [comment]
I've had a go but I was unable to reproduce. Did it run smoothly for several days before showing this behaviour? It could be related to the file handle leak mentioned in #17 if so.

**Comment by tpbowden** [comment]
I've made several improvements and upgrades to the project and is packages since you posted this issue - can you please try again using the latest tag and let me know if this is still happening?

**Comment by pascalandy** [comment]
Sure! Will do tonight. 

---

Be careful with latest tag! 0.3.0 and latest shall be the same in this case. Personally, I push this way:

`docker push $ENV_IMG_NAME_DATE`
	
`docker push $ENV_IMG_NAME_LATEST`

**Comment by tpbowden** [comment]
Not sure what you mean about the tags. The latest tag is always the build using HEAD of the master branch. When I push a tag they are automatically built to the tagged commit using Travis. 0.3.0 is now locked at that tag and will no longer be pushed to unless i manually do so.

**Comment by pascalandy** [comment]
1) I'm still on the case :) As Docker 1.12.2 is out, I want to upgrade my nodes and test hard.

2) I get your point. The issue is that most folks that tries container will use latest by default. So I don't think it's best practice to have latest=master _**as master in your case is an active branch dev**_ and not a stable branch. I think it would make more sense to testing something like V0.4.0RC then latest. 

If you consider master as stable then life is good. Of course this is only my 5 cents :)

**Comment by tpbowden** [comment]
Oh right, I see what you mean. I think that makes sense; when I get time I'll move master to push the dev tag and make latest be the latest numbered stable git tag.

**Comment by pascalandy** [comment]
So far, tag latest is stable over Docker 1.12.2  
Please push an official tag :)

I'll continue to report while messing nodes and other test stress. Cheers!

**Comment by tpbowden** [comment]
Ok 0.3.1 is now released (and the latest tag is now latest stable tag rather than latest commit)

**Comment by pascalandy** [comment]
Thanks for everything!
