### ISSUE TITLE
Sockets are not closed properly?

### ISSUE THREAD

**Issue by norbertgaal** [tpbowden/swarm-ingress-router#17]
I ran into a strange issue, my host reached an open file limit and it looks like the swarm-ingress-cluster container is not closing the docker socket it opens properly.

It looks like the number of open sockets increases by one every ten seconds: 
Just do a `watch -n 10 "lsof | grep socket | wc -l"` inside the container to verify this. 

Using version 0.0.3

**Comment by tpbowden** [comment]
Are you sure you don't mean v0.3.0? v0.0.3 is long dead and was never even completed. Either way I'll look into it on master see what I can find. I'm just using Docker's API project so the issue may live in there.

**Comment by norbertgaal** [comment]
Sorry, it was a typo, of course I meant 0.3.0 :) 
Thank you.

**Comment by tpbowden** [comment]
Yeah you're right I managed to reproduce it easily, but it doesn't happen when I run the project on my Mac. Will look into it further, might be an issue with garbage collection.

**Comment by tpbowden** [comment]
What host OS are you running Docker on?

**Comment by norbertgaal** [comment]
This instance is on an Ubuntu 16.04.1 and I am running Docker version 1.12.1

**Comment by tpbowden** [comment]
OK thanks, struggling to see why this connection is being left laying around at the minute.

**Comment by tpbowden** [comment]
I've made a few changes, including only instantiating a single Docker client, using a pointer receiver for the client and migrating from the deprecated `github.com/docker/engine-api` package to `github.com/docker/docker/client`. Also upgraded to golang 1.7, so hopefully that's everything up to date now. It seems the issue has been fixed as a result. 

Can you please confirm that you no longer have the issue with the latest tag? If so I will bump the version and close this issue.

Thanks for your help.

**Comment by norbertgaal** [comment]
So far so good, looks like the issue is fixed.
Thanks for the quick response!

**Comment by tpbowden** [comment]
OK will close this for now, feel free to re-open / add a new issue if there are any more problems.
