### ISSUE TITLE
Q: Where would I put a Nginx reverse proxy cache?

### ISSUE THREAD

**Issue by johanforssell** [tpbowden/swarm-ingress-router#18]
Are questions ok here?

I would like to put a Nginx reverse proxy/cache in front of my web server. Any suggestions on how to do this in a swarm-ingress-router managed swarm?

**Comment by tpbowden** [comment]
Your proxy cache would just be another service using the ingress router I think, it just needs a different DNS entry. The way I have done this in the past is to have your static files requiring a cache hosted at assets.example.com, whilst your app lives at example.com. Then you can configure nginx to fetch the assets from example.com then cache them to server from assets.example.com. Not sure if you will have an issue with headers being stripped by the proxy, but I haven't investigated that.
