### ISSUE TITLE
Can't get a response from the routed web server

### ISSUE THREAD

**Issue by davemuench** [tpbowden/swarm-ingress-router#19]
I've been trying to get this ingress router set up on my 1.12.3 swarm cluster, and am stuck. I have it set up pretty much according to the example. I have a nginx alpine container set up as in the example named web-test. DNS for it is set up as web-test.example.com via multiple A records pointing at my 3 worker nodes (but not my 3 manager nodes). The router is running on all 6 nodes due to docker bug docker/swarmkit#1570. 

I've verified all router nodes can get a proper response from nginx on the web-test container via telnet. I've verified that the redis store has what looks like a legitimate key:

"[{\"URL\":\"web-test:80\",\"DNSName\":\"web-test.example.com\",\"Secure\":false,\"ForceTLS\":false,\"EncodedCert\":\"\",\"EncodedKey\":\"\"}]"

When I hit it from a web browser I get a blank page. When I test via telnet to one of the worker nodes this happens:

MBP:~ dave$ telnet 1.2.3.4 80
Trying 1.2.3.4...
Connected to docker1.example.com.
Escape character is '^]'.
GET / HTTP/1.1
Host: web-test.example.com

< 40 second pause >

HTTP/1.1 200 OK
Server: fasthttp
Date: Sat, 29 Oct 2016 21:04:13 GMT
Content-Length: 0

Meanwhile, this is what shows in the logs of one of the routers:

2016/10/29 20:30:39 Registering service for web-test.example.com
2016/10/29 20:30:39 Routes updated
2016/10/29 20:30:49 Registering service for web-test.example.com
2016/10/29 20:30:49 Routes updated
2016/10/29 20:30:58 Started GET "/" for 10.255.0.6:39118 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.7:36368 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.5:53796 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.6:39124 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.7:36374 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.5:53802 using host web-test.example.com
2016/10/29 20:30:58 Started GET "/" for 10.255.0.6:39130 using host web-test.example.com

< keeps repeating at a rate of 50-100 per second on random port numbers >

2016/10/29 20:31:37 Started GET "/" for 10.255.0.7:51990 using host web-test.example.com
2016/10/29 20:31:37 Started GET "/" for 10.255.0.5:41190 using host web-test.example.com
2016/10/29 20:31:37 Started GET "/" for 10.255.0.6:54750 using host web-test.example.com
2016/10/29 20:31:39 Registering service for web-test.example.com
2016/10/29 20:31:39 Routes updated

10.255.0.5, 6 and 7 are the ingress IPs for the 3 worker nodes.

I am stumped. One thing that really puzzles me is that the log messages cycle on the 3 ingress IPs for the worker nodes even when I telnet specifically to one of them, not using the round robin DNS. I'd expect if anything it'd either not cycle, or cycle against all 6 nodes including the managers.

Any help would be much appreciated.

(IPs/host names have been sanitized of course)

**Comment by tpbowden** [comment]
At a glance I'm afraid I've got no idea what the issue here is, but I'll try and reproduce when i get time.

**Comment by davemuench** [comment]
Can do. Glad (?) to know it's not something obvious I did wrong.

Is it correct that if I am doing a telnet test to one of the specific node IPs, that I should only see one "Started GET ..." message on one of the ingress IPs, not across all 3?

**Comment by tpbowden** [comment]
Yeah the idea is that a request comes into any node in the Swarm (whether or not it is running the router) on port 80 / 443 depending on TLS config, and the request is proxied to the correct service based on the hostname. So each request should only be served by Nginx once from a single container. Docker's internal round robin DNS / floating IPs handles the load balancing between containers.

**Comment by davemuench** [comment]
I'm back to trying to debug this, and for reasons I can't tell, the behavior has changed. It doesn't look like a new version of the image has been pushed up to the hub, but I no longer get the massive log spam when connecting to it. When testing via telnet, I get a message on one of the router nodes (not necessarily the one DNS chose for my telnet client, but I will have to assume that is due to swarm's own ingress routing) along these lines:

2016/11/08 21:21:57 Started GET "/" for 10.255.0.5:51891 using host web-test.example.com
2016/11/08 21:21:57 0.002 #0000000100000001 - 10.255.0.13:8080<->10.255.0.5:51891 - GET http://web-test.example.com/ - error when proxying the request: dial tcp4 1.2.3.61:8080: getsockopt: connection refused

10.255.0.5 makes sense, that's the ingress IP for the node. As does the 1.2.3.61 address - that's the IP DNS selected for my telnet client, although it is not the IP of the docker node this particular router is running on.

The 10.255.0.13 address is what is confusing me - that's the ingress IP for the router that this was logged on. Why would it be trying to connect to 8080 on that container? Shouldn't it be trying to connect to the internal VIP for the web-test service? Which in this case would be 10.0.0.9.

I'm running out of ideas - I've been going through the code, but the way it's acting has me questioning if I even understand how it is supposed to work.

**Comment by tpbowden** [comment]
Did you ever get to the bottom of this? I could no reproduce so I'm going to close the issue unless you need more help with it.

**Comment by davemuench** [comment]
Afraid not, I gave up and moved on to a different load balancing (and clustering) solution. I appreciate the help.
