### ISSUE TITLE
Ingress router doesn't work without publishing ports on service

### ISSUE THREAD

**Issue by subhashdasyam** [tpbowden/swarm-ingress-router#20]
Hi guys,

I tested the ingress router, 

My setup is CentOS 7, until i specifically give --publish someport:80 -- label targetport=80 

is someone facing the same problem ?

**Comment by tpbowden** [comment]
I haven't tried it on more recent versions of Docker, what version are you using?

**Comment by subhashdasyam** [comment]
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

**Comment by subhashdasyam** [comment]
Hi @tpbowden 
Just trying to understand the working of swarm ingress router
so lets say i have a image which exposes port 8000 only 


in the docker swarm create should i use the publish like 

docker service create --name frontend1 --publish 8778:8000 --label ingress=true --label ingress.dnsname=mydomain.com --label ingress.targetport=9000 --network frontends myimages_with_port_8000_exposed

the above never works when i visit mydomain.com:9000

the below command works when i visit mydomain.com:9000

docker service create --name frontend1 --publish 9000:8000 --label ingress=true --label ingress.dnsname=mydomain.com --label ingress.targetport=9000 --network frontends myimages_with_port_8000_exposed


the below command works when i visit mydomain:80

docker service create --name frontend1 --publish 8776:8000 --label ingress=true --label ingress.dnsname=mydomain.com --label ingress.targetport=80 --network frontends myimages_with_port_8000_exposed


can you please tell me what am i doing wrong

**Comment by tpbowden** [comment]
I think you're using the target port wrong. The idea of setting the `ingress.targetport` label is so the router knows which port on your container to forward the request to. So for example if you've got a container which runs a service exposed on port 8000 (using `EXPOSE 8000` in the dockerfile) then any container on the same network should be able to access this directly. This is why your service has to run on the fronends network along with the router. So the only thing you need to do is set the `ingress.targetport` label to 8000 and it should work without exposing anything in your service.

Hope this is clear

**Comment by subhashdasyam** [comment]
Thanks @tpbowden for clearing up i think this was problem with Docker version 1.12.2
i upgraded to 1.12.3 and this fixed (at least in centos 7) without publishing my ports

a new problem raised now 
I have two services with same dns name mydomain.com 

for one service i set the label ingress.targetport to 80 ( as the image exposes port 80)
another service i set the label ingress.targetport to 9001 (as the image exposes port 9001)

now when i browse mydomain.com:9001 the page doesn't load 
but when i browse mydomain.com:80 the 9001's image loads and it seems first image lost.

**Comment by tpbowden** [comment]
that's because the router only works on standard HTTP / HTTPS ports at the minute (80 and 443). It's only mean to route web traffic.

**Comment by subhashdasyam** [comment]
Thanks @tpbowden 
it make sense now :) 
I will open another enhancement request to route non standard ports as well dynamically

Closing the issue.
