### ISSUE TITLE
Allow Multiple ports to be routed dynamically 

### ISSUE THREAD

**Issue by subhashdasyam** [tpbowden/swarm-ingress-router#21]
Hi @tpbowden 

Ingress router is awesome for HTTP and HTTPS traffic n standard ports, It will be even better if we can allow multiple non standard ports to be routed through this, instead of just 80 and 443
Multiple ports for single domain is addon feature :) 

Hope you consider this for future

**Comment by tpbowden** [comment]
I'm not sure how this would work as for this to happen it would require the Dockerfile to be updated with extra ports under `PUBLISH`, the internal web server to listen on these ports and serve the correct protocol (which could be anything on non-standard ports but I assume you just mean HTTP) and also for these ports to be configured somewhere, probably via the CLI at startup.

It might be easier for you to just fork the project and make the required changes including the ports you want to use as I don't think its possible to allow arbitrary ports to be configured. Something like Nginx or HAProxy is a more suitable tool for this I think. Have you looked at the jwilder/nginx project?

I am open to suggestions if you have an idea of how it could work however!

**Comment by tpbowden** [comment]
Having thought about this it does not fit in with the way Docker works - going to stick with the default ports only being exposed for now.
