### ISSUE TITLE
200 response code when service is down or unreachable

### ISSUE THREAD

**Issue by coryleeio** [tpbowden/swarm-ingress-router#24]
I've noticed if I spin up the router normally:
$ make dev

but for whatever reason the services are unreachable(they are still running migrations for example), the router will return 200s even though it can't route to the service.

The easiest way to show this is to make the front end service unreachable by placing it on another network, but you'll see it more easily with services that aren't immediately available.

This is particularly problematic with CORS preflight requests, since they are responded to with a 200 status code, and (of course), no headers. This causes CORS errors in console when the services go down, since the request is perceived to have succeeded, even though it could not be routed.

I'm adding an error code to the suspect handler in a PR

**Comment by coryleeio** [comment]
https://github.com/tpbowden/swarm-ingress-router/pull/25

**Comment by tpbowden** [comment]
Yes, this seems obvious in hindsight, thanks for the PR

**Comment by coryleeio** [comment]
No worries, thanks for the router =]

**Comment by subhashdasyam** [comment]
Hi @tpbowden, was this pushed to docker hub ?

**Comment by tpbowden** [comment]
It's currently deployed under the dev tag, will bump the version and tag in the next few days and the changes will appear under latest.
