### ISSUE TITLE
Docker 1.13-RC2

### ISSUE THREAD

**Issue by el-liberator** [tpbowden/swarm-ingress-router#27]
Hi 
Some problems with Docker 1.13 rc2, the "router" service behaves strangely :

**docker service ls**
ID            NAME            MODE        REPLICAS  IMAGE
r8dvizn6ch16  router          global      1/**17**      tpbowden/swarm-ingress-router:latest

**docker service ls**
ID            NAME            MODE        REPLICAS  IMAGE
r8dvizn6ch16  router          global      1/**28**      tpbowden/swarm-ingress-router:latest

**docker service ls**
ID            NAME            MODE        REPLICAS  IMAGE
r8dvizn6ch16  router          global      1/**34**      tpbowden/swarm-ingress-router:latest

**docker service ls**
ID            NAME            MODE        REPLICAS  IMAGE
r8dvizn6ch16  router          global      1/**40**      tpbowden/swarm-ingress-router:latest

**docker service logs router**
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:25 Server listening for HTTPS on https://0.0.0.0:8443
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:25 Server listening for HTTP on http://0.0.0.0:8080
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:25 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:31 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:41 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:36:51 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:01 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:11 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:21 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:31 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:41 Routes updated
router.0.q5y9e32hii5e@m130docker2    | 2016/12/05 12:37:51 Routes updated

**systemctl status docker**
Dec 05 13:38:16 m130docker2 docker[5128]: time="2016-12-05T13:38:16.750079567+01:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bzelzq1fn9vl0z2mg5l69pii1 node.session...9vj1atftzk6d0sctyj
Dec 05 13:38:16 m130docker2 docker[5128]: time="2016-12-05T13:38:16.767272489+01:00" level=error msg="task unavailable" method="(*Dispatcher).processUpdates" module=dispatcher task.id=1mkvei79vj1atftzk6d0sctyj
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.129625860+01:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bzelzq1fn9vl0z2mg5l69pii1 node.session...l6fn1aad07e6k259cj
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.159332963+01:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bzelzq1fn9vl0z2mg5l69pii1 node.session...ww9yir03xag37hu4mn
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.169206889+01:00" level=error msg="task unavailable" method="(*Dispatcher).processUpdates" module=dispatcher task.id=8msbknoww9yir03xag37hu4mn
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.169241629+01:00" level=error msg="task unavailable" method="(*Dispatcher).processUpdates" module=dispatcher task.id=wbvnhpsl6fn1aad07e6k259cj
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.270768092+01:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bzelzq1fn9vl0z2mg5l69pii1 node.session...vdx4uretyouo8u1dww
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.271262381+01:00" level=error msg="task unavailable" method="(*Dispatcher).processUpdates" module=dispatcher task.id=l4mvfmfvdx4uretyouo8u1dww
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.272856439+01:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bzelzq1fn9vl0z2mg5l69pii1 node.session...o74aiud23sdwhddilp
Dec 05 13:38:17 m130docker2 docker[5128]: time="2016-12-05T13:38:17.373404703+01:00" level=error msg="task unavailable" method="(*Dispatcher).processUpdates" module=dispatcher task.id=6j4nqwuo74aiud23sdwhddilp

**docker version**
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:
 OS/Arch:             linux/amd64
 Experimental:        true

**Host : RHEL 7.3**

 However, Swarm Ingress Router still works.

**Comment by tpbowden** [comment]
Maybe I'm missing something but it's not entirely clear from the issue what the actual problem is. What's happening here which you would not expect to happen, and what should be happening instead?

**Comment by el-liberator** [comment]
First 
When doing 'docker service ls' the number of replicas increases (1/17 ,  1/28 , 1/34 , 1/40) this is normal operation?
Second
When doing a 'systemctl status docker' some warnings are present

**Comment by tpbowden** [comment]
I'll have a look at the changelog for 1.13 and see if I can figure out what's going wrong - it seems like an issue with the commands used to create the services rather than the code itself. Haven't used 1.13 yet myself so I'm afraid I can't help you at the minute.

Based on my pervious experience with docker releases, it will probably be quite a while before 1.13 is stable enough for production use anyway - my suggestion would be to stick with the latest stable release for now.

**Comment by tpbowden** [comment]
Appreciate it - out of interest how many nodes are you using in your swarm?

**Comment by el-liberator** [comment]
The Swarm cluster that I used for the Docker 1.13 tests has 2 nodes

**Comment by larryboymi** [comment]
We've been using it with smaller replica counts thus far and it's been doing alright for the most part. Just moved to RC3 today.

**Comment by tpbowden** [comment]
Going to close this until 1.13 is stable and then test against it
