### ISSUE TITLE
Use HAProxy and have Collector Dynamically Update HAProxy Config?

### ISSUE THREAD

**Issue by patran** [tpbowden/swarm-ingress-router#29]
Have you considered using HAProxy along with dynamically updated config rather using a router in its own right?

**Comment by tpbowden** [comment]
Yes I had looked into this but it caused many problems related to concurrency and scaling, volume sharing and ssl certificate management along with the need for even more containers. ehazlett/interlock implements a tool which works in this way.

The idea of this project is for a minimal lightweight service which is easy to maintain. I think go's http libraries are fast enough for most use cases

**Comment by patran** [comment]
Cool. Thanks.
