### ISSUE TITLE
Force TLS redirects incorrectly

### ISSUE THREAD

**Issue by ernest-okot** [tpbowden/swarm-ingress-router#33]
Am not sure if this is a bug or expected behaviour. 
With ingress.forcetls=true, a request like `http://domain/some/path` redirects to `https://domain` instead of `https://domain/some/path`

**Comment by tpbowden** [comment]
That information is not exposed during the TLS handshake, so it is impossible as that data is encrypted. You can see all available information during the handshake here: https://golang.org/pkg/crypto/tls/#ClientHelloInfo

**Comment by tpbowden** [comment]
Sorry I've misread your question, this is definitely possible. I'll look into it when I get some time or feel free to send a pull request, you just need to add the request's path onto the redirect URL
