### ISSUE TITLE
Master or V2

### ISSUE THREAD

**Issue by emathias** [tpbowden/swarm-ingress-router#35]
Hi, 

I read in the master README that v2 is a complete rewrite. 

Just wanted to know if it's stable already or I should be using 'master' for the time being. 

Thanks a lot for this awesome tool!

Best!

**Comment by tpbowden** [comment]
Due to the high volume of changes to Swarm and other personal commitments in the last year or so I haven't had time to work on v2 properly. If you're planning on using this in production I would recommend you take a look at http://github.com/containous/traefik which is a very complete solution.
