### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by riemers** [tpbowden/swarm-ingress-router#4]
I am using the setup where i add the crt and key file to it, if i use my browser the dns will find something and ends up on the router if i check with docker logs with below error message:
````
2016/07/19 13:50:52 http: TLS handshake error from 10.0.0.3:61020: Failed to lookup certificate
````
Starting it up like:
````
docker service create --mode global --network frontends --label ingress=true --label ingress.dnsname=something.dev --label ingress.targetport=80 --label ingress.forcetls=true --label ingress.cert="$(cat /tmp/something.crt)" --label ingress.key="$(cat /tmp/something.key)" --name something-dev myprogram
````

And yes running the other docker instance too. Both my nodes in swarm are managers using 1.12 and using the same network name too.

Is there a issue with the format of the keys, since i took my keys from my current nginx setup which works with those crt/key files.

**Comment by tpbowden** [comment]
I think you're missing the label ingress.tls=true

**Comment by tpbowden** [comment]
I think you're missing the label `ingress.tls=true`. I'm currently looking for a way to simplify this and reduce the number of labels required but for now you have to explicitly state whether or not the app is using TLS.

Let me know if this works, if not can you please copy and paste the output of `docker service inspect <your service name>`. (You can hide the content of your private key if need be)

**Comment by riemers** [comment]
That did the trick, looked over it while copy pasting.. i do have mode=global since you want it HA. But as a test i changed my /etc/hosts to point to 1 of the manager/nodes. Then i ran my app on both manager/nodes. Tested the url, worked fine, i could see logs coming into my app. Only when i killed that container that was getting the hits in, i would refresh and it would not go to the other node but instead it waited till the killed container was back up and started serving from there again. I ran the app as global and scalable mode, but that didn't make much difference. Docker 1.12 is nice, you don't need publishport since you can use internal dns but that should also include the nodes on the other server.

**Comment by tpbowden** [comment]
Are you sure your swarm nodes are connected using the correct listen
addresses? It could be a routing issue between your nodes. But yes there
are definitely issues with docker which need to be resolved before this is
ready for production use.

**Comment by riemers** [comment]
Well they see each other and i have added the listen on the default eth0 interface so they can talk to eachother. Service deployments goes fine to all nodes. I'll do some more test and see when it does and doesn't work properly. I also noticed there is no stickyness , so 1 user could have say a website served from multiple nodes. I don't know if that is handy speed wise, but it is not that my apps are doing millions of request per second anyways (so for me its not a big issue, just thought to mention it)

**Comment by tpbowden** [comment]
The non sickness is by design, you should follow the 12 factor app approach
and it isn't necessary. Im not sure of the details but there is some form
of weighted round Robin algorithm being used begin the scenes which decides
where the  request ends up

**Comment by riemers** [comment]
i'll report some feedback when i can test some more..

**Comment by tpbowden** [comment]
Thanks, appreciate the feedback. Might be worth raising with the Docker team if you can get it to consistently occur.

**Comment by riemers** [comment]
Since i cannot reproduce it, but wanted to tell you:
 8056 root      20   0 1117132 884220      0 S   0.8 22.8  52:52.27 swarm-ingress-router
The 22.8% is the memory footprint, machine itself was swapping load of 60, could not debug further but could be potential memory leak? Just posting it here since for now i can't do much else then reboot the machine.

**Comment by tpbowden** [comment]
Yeah that sounds like a memory leak to me since this is a very lightweight process to begin with. What version are you using? I've made quite a few breaking changes recently so this may have been fixed as a result.

**Comment by riemers** [comment]
Yeah noticed the updated information, i am now using the exact same commands as the readme. Was using docker 1.12rc2, updated to rc4 just to be sure (lost my complete swarm config, but thats bleeding edge is suppose)

**Comment by tpbowden** [comment]
Ok, it it happens again please open a new issue with the details and steps to reproduce and I'll look into fixing it asap
