### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by rtorino** [tpbowden/swarm-ingress-router#5]
What does this statement in your README mean? 

> The service must be restricted to run only on master nodes (as it has to query for services).

Can you provide example like using docker-compose?

**Comment by tpbowden** [comment]
Because it polls the docker daemon via the unix socket, it can only run on master nodes. If you run it on a worker node docker will give you an error because it doesn't have a manifest of all running services available. 

This doesn't relate to compose as it only works with the new docker services in 1.12. In order to restrict to manager nodes, you just need to pass the `--constraint node.role=manager` to the service create command

**Comment by rtorino** [comment]
You mean that in your example, the command that creates the frontend service is lacking this option? `--constraint node.role=manager`

**Comment by tpbowden** [comment]
Yes you're right, my example is missing that configuration as this project is still very much a work in progress. The constraint needs to be added to the router service, your frontend should be able to run anywhere.

**Comment by rtorino** [comment]
@tpbowden Thanks. I'm going to try it and give you feedback.

**Comment by rtorino** [comment]
@tpbowden Unfortunately I got `503 (Service Unavailable)` when access through `example.local` and `Failed to look up service` when I tried to access via IP of manager and worker nodes.

**Comment by tpbowden** [comment]
Can you please paste all the commands you ran to get into this state? It's hard to debug without the full picture but it sounds like you're missing / typo'd a label somewhere.

**Comment by rtorino** [comment]
Here are the steps I did:

Create nodes using docker-machine
``` sh
docker-machine create \
	-d virtualbox \
	--virtualbox-memory "2000" \
	--engine-opt="label=com.function=manager" \
	manager01
```

``` sh
docker-machine create \
	-d virtualbox \
	--virtualbox-memory "2000" \
	--engine-opt="label=com.function=worker" \
	worker01
```

Initialize swarm
``` sh
	docker $(docker-machine config manager01) swarm init \
	--listen-addr $(docker-machine ip manager01):2377
```

Join worker node to swarm
``` sh
docker $(docker-machine config worker01) \
	swarm join \
	--secret 5418d56irr3gwxelz9i7j4fy4 \
	--ca-hash sha256:8af3b0077b23b376410e280ff7ead5b6a5046f9f7845207d90fe995848b5aa7f \
	$(docker-machine ip manager01):2377
```

Create overlay network
``` sh
docker network create --driver=overlay frontends
```

Run swarm-ingress-router service on master
``` sh
docker service create \
	--name router \
	-p 80:8080 \
	-p 443:443 \
	--mount target=/var/run/docker.sock,source=/var/run/docker.sock,type=bind \
	--network frontends \
	-e constraint:com.function==manager \
	tpbowden/swarm-ingress-router:latest
```

Run frontend service
``` sh
docker service create \
	--name frontend \
	--label ingress=true \
	--label ingress.dnsname="example.local" \
	--label ingress.targetport=80 \
	--network frontends \
	--label ingress.tls=true \
	--label ingress.forcetls=true \
	--label ingress.cert="$(cat fixtures/cert.crt)" \
	--label ingress.key="$(cat fixtures/key.key)" \
	nginx:stable-alpine
```

**Comment by tpbowden** [comment]
I think your labelling is wrong. Try `--engine-label com.function=<manager or worker>`

**Comment by tpbowden** [comment]
Going to close this as it doesn't seem to relate to a specific issue. If you have any other problems please let me know.

**Comment by tpbowden** [comment]
After a bit more research, I've discovered that you don't need to manually label your manager nodes if using docker 1.12, it's built into swarm kit. You just need to do --constraint node.role==manager when creating a service.
