### ISSUE TITLE
Error when proxying the request

### ISSUE THREAD

**Issue by Thomas0c** [tpbowden/swarm-ingress-router#7]
After setting up the Ingress router in Docker Swarm Mode I get the following error when trying to proxy a `GET` request: `error when proxying the request: too many colons in address http://frontend:80`.

I don't see an option to somehow edit the address, which the Ingress router proxies the request to.
The service was created based on demo app in the `README`.

Thanks in advance.

**Comment by tpbowden** [comment]
Haven't had time to try it out for a while but I'll look into it at the weekend. What version of docker are you using?

**Comment by el-liberator** [comment]
The same here

**Docker version :** 

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Comment by tpbowden** [comment]
OK thanks, looks like it was introduced when the new version of Docker was released, I haven't tested it against anything after the 1.12.0 beta. Should be a simple fix when I get time.

**Comment by el-liberator** [comment]
OK thanks

**Comment by tpbowden** [comment]
Fixed by 2b505b7. Thanks for letting me know guys.

**Comment by el-liberator** [comment]
Hi 
Yes it's fixed , thanks a lot
